<a href="https://colab.research.google.com/github/Epsilonche/NumVerDatenAnalyse21/blob/master/Copy_of_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import matrix

In [ ]:
def generateRandom2DMatrix(rows: int, columns: int, min_value: int, max_value: int) -> np.matrix:
    '''
        Function to generate one random 2d n*m matrix:
        @param: rows:int number of rows
        @param: columns:int number of columns
        @param: min_value:int minimum value of random numbers
        @param: max_value:int maximum value of random numbers

        @Outuput : Matrix of size rows*columns with values ranging between min and max values
    '''
    if(not(isinstance(rows,int))):
        print("rows must be given as an integer")
    elif(not(isinstance(columns,int))):
        print("columns must be given as an integer")
    elif(not(isinstance(min_value,int))): 
        print("min_value must be given as an integer")
    elif(not(isinstance(max_value,int))):
        print("max_value must be given as an integer")
    elif(rows<1):
        print("number of rows must be at least 1")
    elif(columns<1):
        print("number of columns must be at least 1")

    else:
        rand = np.random.randint(min_value, max_value+1, size=(rows, columns))
        generated_matrix = np.matrix(rand)
        return generated_matrix


In [ ]:
def generateRandom2DMatrixSample(size: int, max_rows: int, max_columns: int) -> list:
    '''
        Function to generate a sample containing random 2d-Matrixes of random dimentions
        @param: size:int size of the random sample 
        @param: max_rows:int maximum number of rows
        @param: max_columns:int maximum number of columns

        @Outuput : list of random Matrixes 
    '''
    #local parameters , todo: golbalised parameters 
    min_value=-100
    max_value=100

    if(not(isinstance(size,int))):
        print("rows must be given as an integer")
    elif(not(isinstance(max_rows,int))):
        print("columns must be given as an integer")
    elif(not(isinstance(max_columns,int))): 
        print("min_value must be given as an integer")
    elif(size<1): 
        print("size of sample must be at leat 1")
    else:
        return [generateRandom2DMatrix(np.random.randint(1,max_rows+1),np.random.randint(1,max_columns+1),min_value,max_value) for i in range(size)]


In [ ]:
def diagonalDominantOf( matrix: np.matrix):
    dimention = sqrt(matrix.size)
    for i in range(dimention):
         matrix.itemset((i,i),)
    

In [ ]:
a = generateRandom2DMatrix(3,3,-10,10)
print(a)

a.item(0,1)

[[ -7 -10   8]
 [ -5   8  -3]
 [  5  -5   6]]


-10